## Logistic Regression Modeling for Early Stage Diabetes Risk Prediction

## Part 2.1: Getting familiar with linear algebraic functions

#### Tasks
- Create matrix of size 10*10 with random integer numbers
- Compute the following linear algebric operations on the matrix using built in functions supported in Numpy, Scipy etc.
  - Find inverse of the matrix and print it
  - Calculate dot product of the matrix with same matrix in transpose A.AT
  - Decompose the original matrix using eigen decomposition print the eigen values and eigen vectors
  - Calculate jacobian matrix 
  - Calculate hessian matrix

In [1]:
import numpy as np
random_matrix = np.random.randint(1,10, size=(10, 10))
print(random_matrix)

[[5 8 7 1 1 2 9 6 1 3]
 [3 8 9 9 1 3 7 5 6 3]
 [9 8 5 1 3 8 1 6 8 5]
 [3 7 1 5 4 5 7 1 6 2]
 [3 3 7 6 7 7 5 7 2 5]
 [1 4 4 1 2 1 2 2 5 6]
 [4 7 7 1 7 3 4 1 3 5]
 [7 5 7 3 4 5 9 2 4 2]
 [1 3 9 8 2 7 5 2 3 8]
 [9 1 8 5 4 2 4 4 5 2]]


In [2]:
inverse = np.linalg.inv(random_matrix)
inverse

array([[ 0.13069837, -0.12989652,  0.02493454,  0.12432668, -0.10639308,
        -0.13002214,  0.03755765, -0.19480826,  0.09486976,  0.1896184 ],
       [ 0.06319978,  0.0382854 ,  0.03395477,  0.05670363, -0.06021341,
        -0.10967213,  0.11126126, -0.13333681,  0.01417632, -0.01579003],
       [-0.11740413,  0.13765583,  0.00872193, -0.21309992,  0.02387465,
         0.03434115,  0.03385544,  0.21296778, -0.04849384, -0.10542355],
       [ 0.06256362, -0.01406051, -0.0278095 ,  0.14621061, -0.04494148,
        -0.13367956,  0.03441869, -0.23599822,  0.0943225 ,  0.13661238],
       [-0.05439466, -0.00787289, -0.04116224,  0.02164295,  0.08529105,
         0.01181085,  0.08574917, -0.00318772, -0.07369684,  0.00960593],
       [-0.08592538,  0.01972252,  0.07401297, -0.0695934 ,  0.04908899,
        -0.04614337, -0.04273019,  0.16823169,  0.01823435, -0.13477069],
       [ 0.03685693, -0.04208547, -0.06288104,  0.03192459,  0.01800276,
         0.08470949, -0.08241667,  0.11301297

In [3]:
a=random_matrix.transpose()
b=np.dot(random_matrix,a)
b

array([[271, 266, 232, 178, 219, 123, 199, 244, 200, 193],
       [266, 364, 272, 234, 275, 157, 222, 273, 290, 246],
       [232, 272, 370, 216, 257, 160, 232, 256, 229, 240],
       [178, 234, 216, 215, 194, 111, 173, 212, 187, 159],
       [219, 275, 257, 194, 304, 134, 216, 243, 271, 226],
       [123, 157, 160, 111, 134, 108, 133, 125, 145, 113],
       [199, 222, 232, 173, 216, 133, 224, 218, 202, 183],
       [244, 273, 256, 212, 243, 125, 218, 278, 229, 233],
       [200, 290, 229, 187, 271, 145, 202, 229, 310, 205],
       [193, 246, 240, 159, 226, 113, 183, 233, 205, 252]])

In [4]:
from numpy.linalg import eig
value,vectors=eig(random_matrix)
print(value)
print('.........................................................................................................')
print(vectors)

[45.85528877+0.j         -9.24216667+0.j         -4.8819542 +2.83906514j
 -4.8819542 -2.83906514j -2.32494376+5.67005525j -2.32494376-5.67005525j
  6.88548039+2.01198799j  6.88548039-2.01198799j  3.01485651+1.59458576j
  3.01485651-1.59458576j]
.........................................................................................................
[[ 0.30604504+0.j         -0.14787044+0.j          0.13461407+0.02010763j
   0.13461407-0.02010763j -0.12200287-0.15500371j -0.12200287+0.15500371j
  -0.03845777-0.3218506j  -0.03845777+0.3218506j   0.38503507-0.1467117j
   0.38503507+0.1467117j ]
 [ 0.37558493+0.j         -0.2364441 +0.j          0.02710602+0.26549635j
   0.02710602-0.26549635j -0.22795017+0.10416j    -0.22795017-0.10416j
   0.52524037+0.j          0.52524037-0.j          0.23533039+0.06202084j
   0.23533039-0.06202084j]
 [ 0.36754477+0.j          0.51790924+0.j          0.21261005-0.3203372j
   0.21261005+0.3203372j  -0.05023418+0.26464889j -0.05023418-0.26464889j
  -0.124

In [5]:
import numdifftools as nd
import numpy as np
sigm =lambda x: 1/1+np.exp(-x)
sigmhes= nd.Hessian(sigm)
h= sigmhes([1])
h

array([[0.36787944]])

In [6]:
import sys
!{sys.executable} -m pip install numdifftools

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


## Part 2.2: Logistic Regression using newton method

### Logistic regression
Logistic regression uses an equation as the representation, very much like linear regression.

Input values (x) are combined linearly using weights or coefficient values (referred to as W) to predict an output value (y). A key difference from linear regression is that the output value being modeled is a binary values (0 or 1) rather than a continuous value.<br>

###  $\hat{y}(w, x) = \frac{1}{1+exp^{-(w_0 + w_1 * x_1 + ... + w_p * x_p)}}$

#### Dataset
The dataset is available at <strong>"data/diabetes_data.csv"</strong> in the respective challenge's repo.<br>
<strong>Original Source:</strong> http://archive.ics.uci.edu/ml/machine-learning-databases/00529/diabetes_data_upload.csv. The dataset just got released in July 2020.<br><br>

#### Features (X)

1. Age                - Values ranging from 16-90
2. Gender             - Binary value (Male/Female)
3. Polyuria           - Binary value (Yes/No)
4. Polydipsia         - Binary value (Yes/No)
5. sudden weight loss - Binary value (Yes/No)
6. weakness           - Binary value (Yes/No)
7. Polyphagia         - Binary value (Yes/No)
8. Genital thrush     - Binary value (Yes/No)
9. visual blurring    - Binary value (Yes/No)
10. Itching           - Binary value (Yes/No)
11. Irritability      - Binary value (Yes/No)
12. delayed healing   - Binary value (Yes/No)
13. partial paresis   - Binary value (Yes/No)
14. muscle stiffness  - Binary value (Yes/No)
15. Alopecia          - Binary value (Yes/No)
16. Obesity           - Binary value (Yes/No)

#### Output/Target target (Y) 
17. class - Binary class (Positive/Negative)

#### Objective
To learn logistic regression and practice handling of both numerical and categorical features

#### Tasks
- Download, load the data and print first 5 and last 5 rows
- Transform categorical features into numerical features. Use label encoding or any other suitable preprocessing technique
- Since the age feature is in larger range, age column can be normalized into smaller scale (like 0 to 1) using different methods such as scaling, standardizing or any other suitable preprocessing technique (Example - sklearn.preprocessing.MinMaxScaler class)
- Define X matrix (independent features) and y vector (target feature)
- Split the dataset into 60% for training and rest 40% for testing (sklearn.model_selection.train_test_split function)
- Train Logistic Regression Model on the training set (sklearn.linear_model.LogisticRegression class)
- Use the trained model to predict on testing set
- Print 'Accuracy' obtained on the testing dataset i.e. (sklearn.metrics.accuracy_score function)

#### Further fun (will not be evaluated)
- Plot loss curve (Loss vs number of iterations)
- Preprocess data with different feature scaling methods (i.e. scaling, normalization, standardization, etc) and observe accuracies on both X_train and X_test
- Training model on different train-test splits such as 60-40, 50-50, 70-30, 80-20, 90-10, 95-5 etc. and observe accuracies on both X_train and X_test
- Shuffling of training samples with different *random seed values* in the train_test_split function. Check the model error for the testing data for each setup.
- Print other classification metrics such as:
    - classification report (sklearn.metrics.classification_report),
    - confusion matrix (sklearn.metrics.confusion_matrix),
    - precision, recall and f1 scores (sklearn.metrics.precision_recall_fscore_support)

#### Helpful links
- Scikit-learn documentation for logistic regression: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
- How Logistic Regression works: https://machinelearningmastery.com/logistic-regression-for-machine-learning/
- Feature Scaling: https://scikit-learn.org/stable/modules/preprocessing.html
- Training testing splitting: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
- Classification metrics in sklearn: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics
- Use slack for doubts: https://join.slack.com/t/deepconnectai/shared_invite/zt-givlfnf6-~cn3SQ43k0BGDrG9_YOn4g

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [8]:
# Download the dataset from the source
!wget _URL_

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [9]:
# NOTE: DO NOT CHANGE THE VARIABLE NAME(S) IN THIS CELL
# Load the data
data = pd.read_csv("data/diabetes_data.csv")
data.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [10]:
data.head(5)

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [11]:
lastfive= data.tail()
lastfive

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity     class  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative

In [12]:
# Handle categorical/binary columns
colList = data.select_dtypes(include=[object,float,int]).columns
print (colList)
for feat in colList:
    data[feat] = le.fit_transform(data[feat].astype(str))

print (data.info())

Index(['Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness',
       'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching',
       'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'],
      dtype='object')


NameError: name 'le' is not defined

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data = data[['Age','Gender', 'Polyuria','Polydipsia','sudden weight loss','weakness','Polyphagia','Genital thrush','visual blurring','Itching','Irritability','delayed healing','partial paresis','muscle stiffness','Alopecia','Obesity','class']].apply(le.fit_transform)
data.head()



Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0   16       1         0           1                   0         1   
1   34       1         0           0                   0         1   
2   17       1         1           0                   0         1   
3   21       1         0           0                   1         1   
4   36       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [14]:
#'sudden weight loss','weakness','Polyphagia','Genital thrush','visual blurring','Itching','Irritabality','delayed healing','partial paresis','muscle stiffness','Alopecia','Obesity','class'

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
age1 = scaler.fit_transform(pd.DataFrame(data.Age))
data.Age = age1
data.head()




Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0  0.32       1         0           1                   0         1   
1  0.68       1         0           0                   0         1   
2  0.34       1         1           0                   0         1   
3  0.42       1         0           0                   1         1   
4  0.72       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [16]:
data.insert(0,'intercept',1)
data.head()

intercept   Age  Gender  Polyuria  Polydipsia  sudden weight loss  \
0          1  0.32       1         0           1                   0   
1          1  0.68       1         0           0                   0   
2          1  0.34       1         1           0                   0   
3          1  0.42       1         0           0                   1   
4          1  0.72       1         1           1                   1   

   weakness  Polyphagia  Genital thrush  visual blurring  Itching  \
0         1           0               0                0        1   
1         1           0               0                1        0   
2         1           1               0                0        1   
3         1           1               1                0        1   
4         1           1               0                1        1   

   Irritability  delayed healing  partial paresis  muscle stiffness  Alopecia  \
0             0                1                0                 1         1   
1             0                0                1                 0         1   
2             0                1                0                 1         1   
3             0                1                0                 0         0   
4             1                1                1                 1         1   

   Obesity  class  
0        1      1  
1        0      1  
2        0      1  
3        0      1  
4        1      1

In [34]:
# Define your X and y
X = data.drop(columns=['class'])
y = data['class']


520


In [44]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(312, 17)
(208, 17)
(312,)
(208,)


In [39]:
def predict(X, weights):
    '''Predict class for X.
    For the given dataset, predicted vector has only values 0/1
    Args:
        X : Numpy array (num_samples, num_features)
        weights : Model weights for logistic regression
    Returns:
        Binary predictions : (num_samples,)
    '''

    ### START CODE HERE ###
    z = np.dot(X,weights)
    logits = sigmoid(z)
    y_pred = logits.round()
    ### END CODE HERE ###
    
    return y_pred

In [40]:
def sigmoid(z):
        '''Sigmoid function: f:R->(0,1)
        Args:
            z : A numpy array (num_samples,)
        Returns:
            A numpy array where sigmoid function applied to every element
        '''
        ### START CODE HERE
        sig_z = 1+(1/np.exp(-z))
        ### END CODE HERE
        
        assert (z.shape==sig_z.shape), 'Error in sigmoid implementation. Check carefully'
        return sig_z

In [41]:
def cross_entropy_loss(y_true, y_pred):
    '''Calculate cross entropy loss
    Note: Cross entropy is defined for multiple classes/labels as well
    but for this dataset we only need binary cross entropy loss
    Args:
        y_true : Numpy array of true values (0/1) of size (num_samples,)
        y_pred : Numpy array of predicted values (probabilites) of size (num_samples,)
    Returns:
        Cross entropy loss: A scalar value
    '''
    # Fix 0 values in y_pred
    y_pred = np.maximum(np.full(y_pred.shape, 1e-7), np.minimum(np.full(y_pred.shape, 1-1e-7), y_pred))
    
    ### START CODE HERE
    ce_loss = np.sum(-y_true*np.log(y_pred) - (1-y_true)*np.log(1-y_pred))
    ### END CODE HERE
    
    return ce_loss

In [42]:
def newton_optimization(X, y, max_iterations=25):
    '''Implement netwon method for optimizing weights
    Args:
        X : Numpy array (num_samples, num_features)
        max_iterations : Max iterations to update the weights
    Returns:
        Optimal weights (num_features,)
    '''
    num_samples = X.shape[0]
    print(num_samples)
    num_features = X.shape[1]
    print(num_features)
    # Initialize random weights
    weights = np.zeros(num_features,)
    print(weights)
    # Initialize losses
    losses = []
    
    # Newton Method
    for i in range(max_iterations):
        # Predict/Calculate probabilties using sigmoid function
        y_p = sigmoid(np.dot(X,weights))
        
        # Define gradient for J (cost function) i.e. cross entropy loss
        gradient = ((1/num_samples)*X.T) @ (y_p - y)
        
        # Define hessian matrix for cross entropy loss
        hessian =  ((1/num_samples)*X.T) @ (np.diag(y_p)) @ (np.diag(1-y_p)) @ X
        
        # Update the model using hessian matrix and gradient computed
        weights = weights - np.dot(np.linalg.pinv(hessian),gradient)
        
        # Calculate cross entropy loss
        loss = cross_entropy_loss(y, y_p)
        # Append it
        losses.append(loss)

    return weights, losses

In [43]:
# Train weights
weights, losses = newton_optimization(X_train, y_train)

312
17
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: matrices are not aligned

In [24]:
# Plot the loss curve
import matplotlib as plt
plt.plot([i+1 for i in range(len(losses))], losses)
plt.title("Loss curve")
plt.xlabel("Iteration num")
plt.ylabel("Cross entropy curve")
plt.show()

AttributeError: module 'matplotlib' has no attribute 'plot'

In [25]:
our_model_test_acuracy = accuracy_score(y_test, predict(X_test, weights))

print(f"\nAccuracy in testing set by our model: {our_model_test_acuracy}")

NameError: name 'weights' is not defined

#### Compare with the scikit learn implementation

In [26]:
# Initialize the model
model = LogisticRegression(solver='newton-cg', verbose=1)

In [27]:
# Fit the model. Wait! We will complete this step for you ;)
model.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
          verbose=1, warm_start=False)

In [28]:
# Predict on testing set X_test
y_pred = model.predict(X_test)

In [29]:
# Print Accuracy on testing set
sklearn_test_accuracy = accuracy_score(y_test, y_pred)

print(f"\nAccuracy in testing set by sklearn model: {sklearn_test_accuracy}")


Accuracy in testing set by sklearn model: 0.9230769230769231
